// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FrietzaakDBContext))]
    [Migration("20240930103957_MoreItems")]
    partial class MoreItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerID"));

                    b.Property<string>("Emailadres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gebruikersnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuisnummerToevoeging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GebruikerID");

                    b.ToTable("Gebruikers");

                    b.HasData(
                        new
                        {
                            GebruikerID = 1,
                            Emailadres = "henk@gmail.com",
                            Gebruikersnaam = "henk",
                            Huisnummer = "69",
                            HuisnummerToevoeging = "b",
                            Plaats = "Heerlen",
                            Straat = "HuisWeg",
                            Telefoonnummer = "0669476936"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<bool?>("Afgehandeld")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BestelDatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("GebruikerID")
                        .HasColumnType("int");

                    b.Property<double?>("Totaalprijs")
                        .HasColumnType("float");

                    b.HasKey("OrderID");

                    b.HasIndex("GebruikerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApplication1.Models.OrderLine", b =>
                {
                    b.Property<int>("OrderLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineID"));

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderID1")
                        .HasColumnType("int");

                    b.Property<int?>("PoductAmount")
                        .HasColumnType("int");

                    b.Property<string>("ProductID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductID1")
                        .HasColumnType("int");

                    b.Property<int?>("Productprijs")
                        .HasColumnType("int");

                    b.HasKey("OrderLineID");

                    b.HasIndex("OrderID1");

                    b.HasIndex("ProductID1");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("OrderlineID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductBeschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrijs")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductNaam = "Frikandel",
                            ProductPrijs = 2.25
                        },
                        new
                        {
                            ProductID = 2,
                            ProductNaam = "Kleine friet",
                            ProductPrijs = 2.0
                        },
                        new
                        {
                            ProductID = 3,
                            ProductNaam = "Medium friet",
                            ProductPrijs = 3.5
                        },
                        new
                        {
                            ProductID = 4,
                            ProductNaam = "Grote friet",
                            ProductPrijs = 4.25
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.HasOne("WebApplication1.Models.Gebruiker", "Gebruiker")
                        .WithMany("Orders")
                        .HasForeignKey("GebruikerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("WebApplication1.Models.OrderLine", b =>
                {
                    b.HasOne("WebApplication1.Models.Order", "Order")
                        .WithMany("OrderLine")
                        .HasForeignKey("OrderID1");

                    b.HasOne("WebApplication1.Models.Product", "Product")
                        .WithMany("Orderlines")
                        .HasForeignKey("ProductID1");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebApplication1.Models.Gebruiker", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.Navigation("OrderLine");
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Navigation("Orderlines");
                });
#pragma warning restore 612, 618
        }
    }
}
