// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(FrietzaakDBContext))]
    [Migration("20240927080315_OrderLine")]
    partial class OrderLine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Models.Gebruiker", b =>
                {
                    b.Property<int>("GebruikerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GebruikerID"));

                    b.Property<string>("Emailadres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gebruikersnaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Huisnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HuisnummerToevoeging")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plaats")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Straat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefoonnummer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GebruikerID");

                    b.ToTable("Gebruikers");

                    b.HasData(
                        new
                        {
                            GebruikerID = 1,
                            Emailadres = "henk@gmail.com",
                            Gebruikersnaam = "henk",
                            Huisnummer = "69",
                            HuisnummerToevoeging = "b",
                            Plaats = "Heerlen",
                            Straat = "HuisWeg",
                            Telefoonnummer = "0669476936"
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"));

                    b.Property<int>("GebruikerID")
                        .HasColumnType("int");

                    b.Property<string>("OrderLineID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderID");

                    b.HasIndex("GebruikerID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebApplication1.Models.OrderLine", b =>
                {
                    b.Property<int>("OrderLineID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderLineID"));

                    b.Property<string>("GebruikerID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GebruikerID1")
                        .HasColumnType("int");

                    b.Property<string>("OrderID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderID1")
                        .HasColumnType("int");

                    b.Property<int?>("PoductAmount")
                        .HasColumnType("int");

                    b.Property<int?>("Productprijs")
                        .HasColumnType("int");

                    b.HasKey("OrderLineID");

                    b.HasIndex("GebruikerID1");

                    b.HasIndex("OrderID1");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("WebApplication1.Models.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<string>("ProductBeschrijving")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductNaam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ProductPrijs")
                        .HasColumnType("float");

                    b.HasKey("ProductID");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            ProductNaam = "Frikandel",
                            ProductPrijs = 2.25
                        });
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.HasOne("WebApplication1.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("GebruikerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gebruiker");
                });

            modelBuilder.Entity("WebApplication1.Models.OrderLine", b =>
                {
                    b.HasOne("WebApplication1.Models.Gebruiker", "Gebruiker")
                        .WithMany()
                        .HasForeignKey("GebruikerID1");

                    b.HasOne("WebApplication1.Models.Order", "Order")
                        .WithMany("OrderLine")
                        .HasForeignKey("OrderID1");

                    b.Navigation("Gebruiker");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("WebApplication1.Models.Order", b =>
                {
                    b.Navigation("OrderLine");
                });
#pragma warning restore 612, 618
        }
    }
}
